version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0-browsers
    steps:
      - checkout
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.1.0-browsers
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci-kbdemo-ruby
          POSTGRES_DB: rails_kbdemo_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGDB: rails_kbdemo_test
      PGUSER: circleci-kbdemo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-browser-tools
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp config/database.yml.example config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run all tests using Rails
          command: RAILS_ENV=test bundle exec rails test:all
      - store_test_results:
          path: test/reports
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
